// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9e3xwNCsguWabwcJEoSzMPGjl0ynUKdc',
    appId: '1:702988744727:web:8e3d05340834a695648452',
    messagingSenderId: '702988744727',
    projectId: 'paswan-a8f8e',
    authDomain: 'paswan-a8f8e.firebaseapp.com',
    storageBucket: 'paswan-a8f8e.appspot.com',
    measurementId: 'G-WL9BGBMHBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg8aDZ97HEBbV2XoOQyMgGM0LAJwCBZuM',
    appId: '1:702988744727:android:f5ca2e26d9c2e502648452',
    messagingSenderId: '702988744727',
    projectId: 'paswan-a8f8e',
    storageBucket: 'paswan-a8f8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsDi6PWw_jKv-MjXkVIYvcfzuqaQJrqNU',
    appId: '1:702988744727:ios:ad95c0495da91dd6648452',
    messagingSenderId: '702988744727',
    projectId: 'paswan-a8f8e',
    storageBucket: 'paswan-a8f8e.appspot.com',
    iosBundleId: 'com.example.aepka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsDi6PWw_jKv-MjXkVIYvcfzuqaQJrqNU',
    appId: '1:702988744727:ios:ad95c0495da91dd6648452',
    messagingSenderId: '702988744727',
    projectId: 'paswan-a8f8e',
    storageBucket: 'paswan-a8f8e.appspot.com',
    iosBundleId: 'com.example.aepka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9e3xwNCsguWabwcJEoSzMPGjl0ynUKdc',
    appId: '1:702988744727:web:18119e8c8636391a648452',
    messagingSenderId: '702988744727',
    projectId: 'paswan-a8f8e',
    authDomain: 'paswan-a8f8e.firebaseapp.com',
    storageBucket: 'paswan-a8f8e.appspot.com',
    measurementId: 'G-GXTXLEDJ61',
  );
}
